# Generated by Django 3.2 on 2021-12-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityaddress',
            name='address_line_three',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='charityaddress',
            name='address_line_two',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='charityaddress',
            name='postcode',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
