# Generated by Django 3.2 on 2021-12-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityaddress',
            name='address_line_one',
            field=models.CharField(default='sdsad', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charityaddress',
            name='organisation_name',
            field=models.CharField(default='dsfsdfsf', max_length=150),
            preserve_default=False,
        ),
    ]
