# Generated by Django 3.2 on 2021-12-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211209_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityaddress',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
