# Generated by Django 3.2 on 2021-12-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211210_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organisation_name',
            field=models.CharField(max_length=150),
        ),
    ]
