# Generated by Django 3.2 on 2021-12-12 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organisation_name', models.CharField(max_length=1550)),
                ('description', models.CharField(max_length=1550)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('age_range', models.CharField(choices=[('0-1', '0-1'), ('1-3', '1-3'), ('3-5', '3-5'), ('6-7', '6-7'), ('7-10', '7-10'), ('10-13', '10-13'), ('13-16', '13-16')], max_length=25)),
                ('image', models.ImageField(blank=True, upload_to='gift_images/')),
                ('needed', models.BooleanField(default=True)),
                ('committed', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
