# Generated by Django 3.2 on 2021-12-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_auto_20211209_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, upload_to='gift_images/'),
        ),
    ]
