# Generated by Django 3.2 on 2021-12-11 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_gift_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
