# Generated by Django 3.2 on 2021-12-11 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0007_alter_donation_donation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.gift'),
        ),
    ]
