# Generated by Django 3.2 on 2021-12-11 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0010_alter_donation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='user',
        ),
        migrations.AddField(
            model_name='gift',
            name='organisation_name',
            field=models.CharField(default='dfdsf', max_length=1550),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gift',
            name='committed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
